"""
Strategy Categorization Library

Maps cryptocurrency assets to strategy tiers (Collateral/Growth/Wildcard)
based on market cap, stability, and risk profile.
"""

from typing import Literal

StrategyTier = Literal["Collateral", "Growth", "Wildcard"]

# Asset categorization mapping
ASSET_CATEGORIES: dict[str, StrategyTier] = {
    # Collateral Tier - Large cap, stable, established cryptocurrencies
    "BTC": "Collateral",
    "ETH": "Collateral",
    "BNB": "Collateral",
    "USDT": "Collateral",
    "USDC": "Collateral",
    "BUSD": "Collateral",
    "DAI": "Collateral",
    "WBTC": "Collateral",
    "WETH": "Collateral",
    "STETH": "Collateral",
    
    # Growth Tier - Mid cap, established projects with growth potential
    "ADA": "Growth",
    "SOL": "Growth",
    "DOT": "Growth",
    "AVAX": "Growth",
    "MATIC": "Growth",
    "LINK": "Growth",
    "UNI": "Growth",
    "ATOM": "Growth",
    "NEAR": "Growth",
    "ALGO": "Growth",
    "VET": "Growth",
    "ICP": "Growth",
    "FIL": "Growth",
    "AAVE": "Growth",
    "MKR": "Growth",
    "COMP": "Growth",
    "SUSHI": "Growth",
    "CRV": "Growth",
    "YFI": "Growth",
    "SNX": "Growth",
    "RUNE": "Growth",
    "LUNA": "Growth",
    "FTM": "Growth",
    "ONE": "Growth",
    "HBAR": "Growth",
    "EGLD": "Growth",
    "THETA": "Growth",
    "TFUEL": "Growth",
    "KSM": "Growth",
    "FLOW": "Growth",
    "MANA": "Growth",
    "SAND": "Growth",
    "AXS": "Growth",
    "ENJ": "Growth",
    "CHZ": "Growth",
    "BAT": "Growth",
    "ZRX": "Growth",
    "LRC": "Growth",
    "GRT": "Growth",
    "BAND": "Growth",
    "REN": "Growth",
    "STORJ": "Growth",
    "OCEAN": "Growth",
    "FET": "Growth",
    "AGIX": "Growth",
    "RNDR": "Growth",
    "INDR": "Growth",
    
    # Wildcard Tier - Small cap, high risk/reward, experimental projects
    "SHIB": "Wildcard",
    "DOGE": "Wildcard",
    "PEPE": "Wildcard",
    "FLOKI": "Wildcard",
    "BONK": "Wildcard",
    "WIF": "Wildcard",
    "MEME": "Wildcard",
    "WOJAK": "Wildcard",
    "TURBO": "Wildcard",
    "LADYS": "Wildcard",
    "PEPECOIN": "Wildcard",
    "BABYDOGE": "Wildcard",
    "SAFEMOON": "Wildcard",
    "AKITA": "Wildcard",
    "KISHU": "Wildcard",
    "ELON": "Wildcard",
    "DOGELON": "Wildcard",
    "CATGIRL": "Wildcard",
    "SAITAMA": "Wildcard",
    "LUFFY": "Wildcard",
    "GALA": "Wildcard",
    "IMX": "Wildcard",
    "GMT": "Wildcard",
    "APE": "Wildcard",
    "LOOKS": "Wildcard",
    "BLUR": "Wildcard",
    "MAGIC": "Wildcard",
    "TLM": "Wildcard",
    "SLP": "Wildcard",
    "ALICE": "Wildcard",
    "PYR": "Wildcard",
    "GHST": "Wildcard",
    "REVV": "Wildcard",
    "SUPER": "Wildcard",
    "TVK": "Wildcard",
    "NFTX": "Wildcard",
    "RARI": "Wildcard",
    "WHALE": "Wildcard",
    "MASK": "Wildcard",
    "AUDIO": "Wildcard",
    "DYDX": "Wildcard",
    "INJ": "Wildcard",
    "PERP": "Wildcard",
    "GMX": "Wildcard",
    "JOE": "Wildcard",
    "PNG": "Wildcard",
    "SPELL": "Wildcard",
    "ICE": "Wildcard",
    "TIME": "Wildcard",
    "MEMO": "Wildcard",
    "OHM": "Wildcard",
    "KLIMA": "Wildcard",
    "ROME": "Wildcard",
    "BTRFLY": "Wildcard",
    "TOKE": "Wildcard",
    "FXS": "Wildcard",
    "FRAX": "Wildcard",
    "CVX": "Wildcard",
    "BADGER": "Wildcard",
    "DIGG": "Wildcard",
    "FARM": "Wildcard",
    "PICKLE": "Wildcard",
    "CREAM": "Wildcard",
    "ALPHA": "Wildcard",
    "BNT": "Wildcard",
    "KNC": "Wildcard",
    "MLN": "Wildcard",
    "NMR": "Wildcard",
    "REP": "Wildcard",
    "AUGUR": "Wildcard",
    "GNOSIS": "Wildcard",
    "GNO": "Wildcard",
    "COW": "Wildcard",
    "SAFE": "Wildcard",
    "TAO": "Wildcard",
    "ARB": "Wildcard",
    "OP": "Wildcard",
    "ZEUS": "Wildcard",
    "POKT": "Wildcard",
    "RAY": "Wildcard",
    "SRM": "Wildcard",
    "FIDA": "Wildcard",
    "ROPE": "Wildcard",
    "COPE": "Wildcard",
    "STEP": "Wildcard",
    "MEDIA": "Wildcard",
    "TULIP": "Wildcard",
    "SLIM": "Wildcard",
    "BOP": "Wildcard",
    "SAMO": "Wildcard",
    "NINJA": "Wildcard",
    "GRAPE": "Wildcard",
    "CHEEMS": "Wildcard",
    "DUST": "Wildcard",
    "FORGE": "Wildcard",
    "STAR": "Wildcard",
    "ATLAS": "Wildcard",
    "POLIS": "Wildcard",
    "ORCA": "Wildcard",
    "MNGO": "Wildcard",
    "MSOL": "Wildcard",
    "STSOL": "Wildcard",
    "SCNSOL": "Wildcard",
    "JSOL": "Wildcard",
    "BSOL": "Wildcard",
    "DAOSOL": "Wildcard",
    "LARIX": "Wildcard",
    "PORT": "Wildcard",
    "SUNNY": "Wildcard",
    "SLRS": "Wildcard",
    "CRWNY": "Wildcard",
    "SOLAPE": "Wildcard",
    "SONAR": "Wildcard",
    "SLND": "Wildcard",
    "JET": "Wildcard",
    "APYS": "Wildcard",
    "CASH": "Wildcard",
    "BASIS": "Wildcard",
    "GST": "Wildcard",
    "SWEAT": "Wildcard",
    "FITFI": "Wildcard",
    "DOSE": "Wildcard",
    "CALO": "Wildcard",
}


def categorize_asset(symbol: str) -> StrategyTier:
    """
    Categorizes a crypto asset into a strategy tier.
    
    Args:
        symbol: The crypto symbol (e.g., 'BTC', 'ETH')
        
    Returns:
        The strategy tier for the asset (Collateral/Growth/Wildcard)
        Defaults to Wildcard for unknown assets
    """
    upper_symbol = symbol.upper()
    return ASSET_CATEGORIES.get(upper_symbol, "Wildcard")
